name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
permissions: write-all
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
      - name: Generate linux amd64 build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: "1.23"
          build_command: "make build"
          binary_name: wiim-mqtt
          compress_assets: false
          release_tag: ${{ github.ref_name }}
          retry: 10
          overwrite: true
      - name: Generate linux arm64 build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: arm64
          goversion: "1.23"
          build_command: "make build"
          binary_name: wiim-mqtt
          compress_assets: false
          release_tag: ${{ github.ref_name }}
          retry: 10
          overwrite: true
      - name: Generate linux arm build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: arm
          goversion: "1.23"
          build_command: "make build"
          binary_name: wiim-mqtt
          compress_assets: false
          release_tag: ${{ github.ref_name }}
          retry: 10
          overwrite: true
      - name: Generate darwin amd64 build
        uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: darwin
          goarch: amd64
          goversion: "1.23"
          build_command: "make build"
          binary_name: wiim-mqtt
          compress_assets: false
          release_tag: ${{ github.ref_name }}
          retry: 10
          overwrite: true
